
version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:12.14.1-buster
    steps:
      - checkout
      - run:
          name: Remove node_modules
          command: rm -rf node_modules/
      - run:
          name: Install local dependencies
          command: |
            npm install
      - run:
          name: Check code quality
          command: npm run lint
  test:
    docker:
      - image: circleci/node:12.14.1-buster
    environment:
      NODE_ENV: test
    steps:
      - checkout
      - run:
          name: Remove node_modules
          command: rm -rf node_modules/
      - run:
          name: Install local dependencies
          command: |
            npm install
            npm run test
      - run:
          name: Run tests
          command: npm run test
  build:
    docker:
      - image: circleci/node:12.14.1-buster
    steps:
      - checkout
      - run:
          name: Remove node_modules
          command: rm -rf node_modules/
      - run:
          name: Install local dependencies
          command: |
            npm install
      - run:
          name: Build app
          command: npm run build
      - run:
          name: Change package name to @storeworkflows/ui-kit
          command: npm run rename
      - run:
          name: Delete unnecessary informations
          command: rm -rf .storybook/ storybook-static/ node_modules/ src/ .circleci/ .idea/ .gitignore package-lock.json build-storybook.log .babelrc
      - persist_to_workspace:
          root: .
          paths:
            - ./
  deploy:
    docker:
      - image: storeworkflows/node:12.14.1-buster-rsync
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Add github.com to known_hosts
          command: mkdir ~/.ssh && echo $GITHUB_PUBLIC_KEY >> ~/.ssh/known_hosts
      - run:
          name: Deploy to @storeworkflows/ui-kit
          command: |
            git config --global user.name "StoreWorkflow"
            git config --global user.email "accounting@storeworkflows.com"
            git clone git@github.com:storeworkflows/ui-kit.git
            rsync --checksum --recursive --links --exclude=.git --exclude=ui-kit --delete ./ ui-kit
            cd ui-kit && git add --all && git commit --message="Deploy $CIRCLE_BUILD_NUM" && git branch -M main && git push -u origin main
  chromatic-deployment:
      docker:
        - image: circleci/node:12.14.1-buster
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-
        - run: npm install
        - run: npm chromatic --project-token=${CHROMATIC_PROJECT_TOKEN}
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - main
      - test:
          filters:
            branches:
              only:
                - main
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          context: storeworkflows
          requires:
            - lint
            - test
            - build